[project]
name = "postcraft-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.120.4",
    "httpx>=0.28.1",
    "pydantic>=2.12.3",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
